import '../../../services/music_service.dart';
import '../../../ui/utils/theme_controller.dart';

abstract class SettingsRepository {
  String getAppLanguage();
  Future<void> setAppLanguage(String languageCode);
  int getHomeScreenContentNumber();
  Future<void> setHomeScreenContentNumber(int number);
  AudioQuality getStreamingQuality();
  Future<void> setStreamingQuality(AudioQuality quality);
  int getPlayerUi();
  Future<void> setPlayerUi(int ui);
  bool isBottomNavBarEnabled();
  Future<void> setBottomNavBarEnabled(bool enabled);
  bool isSlidableActionEnabled();
  Future<void> setSlidableActionEnabled(bool enabled);
  String getDownloadingFormat();
  Future<void> setDownloadingFormat(String format);
  Future<String> getExportedLocation();
  Future<void> setExportedLocation();
  Future<String> getDownloadLocation();
  Future<void> setDownloadLocation();
  Future<void> resetDownloadLocation();
  bool isTransitionAnimationDisabled();
  Future<void> setTransitionAnimationDisabled(bool disabled);
  Future<void> clearImagesCache();
  ThemeType getThemeMode();
  Future<void> setThemeMode(ThemeType theme);
  String getDiscoverContentType();
  Future<void> setDiscoverContentType(String type);
  bool isCachingSongsEnabled();
  Future<void> setCachingSongsEnabled(bool enabled);
  bool isSkipSilenceEnabled();
  Future<void> setSkipSilenceEnabled(bool enabled);
  bool isLoudnessNormalizationEnabled();
  Future<void> setLoudnessNormalizationEnabled(bool enabled);
  bool shouldRestorePlaybackSession();
  Future<void> setRestorePlaybackSession(bool restore);
  bool isCacheHomeScreenDataEnabled();
  Future<void> setCacheHomeScreenDataEnabled(bool enabled);
  bool isAutoDownloadFavoriteSongEnabled();
  Future<void> setAutoDownloadFavoriteSongEnabled(bool enabled);
  bool isBackgroundPlayEnabled();
  Future<void> setBackgroundPlayEnabled(bool enabled);
  Future<bool> isIgnoringBatteryOptimizations();
  Future<void> enableIgnoringBatteryOptimizations();
  bool shouldAutoOpenPlayer();
  Future<void> setAutoOpenPlayer(bool open);
  Future<bool> isPipedLinked();
  Future<void> unlinkPiped();
  Future<void> resetAppSettingsToDefault();
  bool shouldStopPlaybackOnSwipeAway();
  Future<void> setStopPlaybackOnSwipeAway(bool stop);
}
