import 'package:get/get.dart';

import '../../../data/settings/repository/settings_repository_impl.dart';
import '../../../domain/settings/repository/settings_repository.dart';
import '../../../domain/settings/usecases/clear_images_cache_usecase.dart';
import '../../../domain/settings/usecases/enable_ignoring_battery_optimizations_usecase.dart';
import '../../../domain/settings/usecases/get_app_language_usecase.dart';
import '../../../domain/settings/usecases/get_discover_content_type_usecase.dart';
import '../../../domain/settings/usecases/get_download_location_usecase.dart';
import '../../../domain/settings/usecases/get_downloading_format_usecase.dart';
import '../../../domain/settings/usecases/get_exported_location_usecase.dart';
import '../../../domain/settings/usecases/get_home_screen_content_number_usecase.dart';
import '../../../domain/settings/usecases/get_player_ui_usecase.dart';
import '../../../domain/settings/usecases/get_streaming_quality_usecase.dart';
import '../../../domain/settings/usecases/get_theme_mode_usecase.dart';
import '../../../domain/settings/usecases/is_auto_download_favorite_song_enabled_usecase.dart';
import '../../../domain/settings/usecases/is_background_play_enabled_usecase.dart';
import '../../../domain/settings/usecases/is_bottom_nav_bar_enabled_usecase.dart';
import '../../../domain/settings/usecases/is_cache_home_screen_data_enabled_usecase.dart';
import '../../../domain/settings/usecases/is_caching_songs_enabled_usecase.dart';
import '../../../domain/settings/usecases/is_ignoring_battery_optimizations_usecase.dart';
import '../../../domain/settings/usecases/is_loudness_normalization_enabled_usecase.dart';
import '../../../domain/settings/usecases/is_piped_linked_usecase.dart';
import '../../../domain/settings/usecases/is_skip_silence_enabled_usecase.dart';
import '../../../domain/settings/usecases/is_slidable_action_enabled_usecase.dart';
import '../../../domain/settings/usecases/is_transition_animation_disabled_usecase.dart';
import '../../../domain/settings/usecases/reset_app_settings_to_default_usecase.dart';
import '../../../domain/settings/usecases/reset_download_location_usecase.dart';
import '../../../domain/settings/usecases/set_app_language_usecase.dart';
import '../../../domain/settings/usecases/set_auto_download_favorite_song_enabled_usecase.dart';
import '../../../domain/settings/usecases/set_auto_open_player_usecase.dart';
import '../../../domain/settings/usecases/set_background_play_enabled_usecase.dart';
import '../../../domain/settings/usecases/set_bottom_nav_bar_enabled_usecase.dart';
import '../../../domain/settings/usecases/set_cache_home_screen_data_enabled_usecase.dart';
import '../../../domain/settings/usecases/set_caching_songs_enabled_usecase.dart';
import '../../../domain/settings/usecases/set_discover_content_type_usecase.dart';
import '../../../domain/settings/usecases/set_download_location_usecase.dart';
import '../../../domain/settings/usecases/set_downloading_format_usecase.dart';
import '../../../domain/settings/usecases/set_exported_location_usecase.dart';
import '../../../domain/settings/usecases/set_home_screen_content_number_usecase.dart';
import '../../../domain/settings/usecases/set_loudness_normalization_enabled_usecase.dart';
import '../../../domain/settings/usecases/set_player_ui_usecase.dart';
import '../../../domain/settings/usecases/set_restore_playback_session_usecase.dart';
import '../../../domain/settings/usecases/set_skip_silence_enabled_usecase.dart';
import '../../../domain/settings/usecases/set_slidable_action_enabled_usecase.dart';
import '../../../domain/settings/usecases/set_stop_playback_on_swipe_away_usecase.dart';
import '../../../domain/settings/usecases/set_streaming_quality_usecase.dart';
import '../../../domain/settings/usecases/set_theme_mode_usecase.dart';
import '../../../domain/settings/usecases/set_transition_animation_disabled_usecase.dart';
import '../../../domain/settings/usecases/should_auto_open_player_usecase.dart';
import '../../../domain/settings/usecases/should_restore_playback_session_usecase.dart';
import '../../../domain/settings/usecases/should_stop_playback_on_swipe_away_usecase.dart';
import '../../../domain/settings/usecases/unlink_piped_usecase.dart';

class SettingsBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<SettingsRepository>(() => SettingsRepositoryImpl());
    Get.lazyPut(() => GetAppLanguageUseCase());
    Get.lazyPut(() => SetAppLanguageUseCase());
    Get.lazyPut(() => GetHomeScreenContentNumberUseCase());
    Get.lazyPut(() => SetHomeScreenContentNumberUseCase());
    Get.lazyPut(() => GetStreamingQualityUseCase());
    Get.lazyPut(() => SetStreamingQualityUseCase());
    Get.lazyPut(() => GetPlayerUiUseCase());
    Get.lazyPut(() => SetPlayerUiUseCase());
    Get.lazyPut(() => IsBottomNavBarEnabledUseCase());
    Get.lazyPut(() => SetBottomNavBarEnabledUseCase());
    Get.lazyPut(() => IsSlidableActionEnabledUseCase());
    Get.lazyPut(() => SetSlidableActionEnabledUseCase());
    Get.lazyPut(() => GetDownloadingFormatUseCase());
    Get.lazyPut(() => SetDownloadingFormatUseCase());
    Get.lazyPut(() => GetExportedLocationUseCase());
    Get.lazyPut(() => SetExportedLocationUseCase());
    Get.lazyPut(() => GetDownloadLocationUseCase());
    Get.lazyPut(() => SetDownloadLocationUseCase());
    Get.lazyPut(() => ResetDownloadLocationUseCase());
    Get.lazyPut(() => IsTransitionAnimationDisabledUseCase());
    Get.lazyPut(() => SetTransitionAnimationDisabledUseCase());
    Get.lazyPut(() => ClearImagesCacheUseCase());
    Get.lazyPut(() => GetThemeModeUseCase());
    Get.lazyPut(() => SetThemeModeUseCase());
    Get.lazyPut(() => GetDiscoverContentTypeUseCase());
    Get.lazyPut(() => SetDiscoverContentTypeUseCase());
    Get.lazyPut(() => IsCachingSongsEnabledUseCase());
    Get.lazyPut(() => SetCachingSongsEnabledUseCase());
    Get.lazyPut(() => IsSkipSilenceEnabledUseCase());
    Get.lazyPut(() => SetSkipSilenceEnabledUseCase());
    Get.lazyPut(() => IsLoudnessNormalizationEnabledUseCase());
    Get.lazyPut(() => SetLoudnessNormalizationEnabledUseCase());
    Get.lazyPut(() => ShouldRestorePlaybackSessionUseCase());
    Get.lazyPut(() => SetRestorePlaybackSessionUseCase());
    Get.lazyPut(() => IsCacheHomeScreenDataEnabledUseCase());
    Get.lazyPut(() => SetCacheHomeScreenDataEnabledUseCase());
    Get.lazyPut(() => IsAutoDownloadFavoriteSongEnabledUseCase());
    Get.lazyPut(() => SetAutoDownloadFavoriteSongEnabledUseCase());
    Get.lazyPut(() => IsBackgroundPlayEnabledUseCase());
    Get.lazyPut(() => SetBackgroundPlayEnabledUseCase());
    Get.lazyPut(() => IsIgnoringBatteryOptimizationsUseCase());
    Get.lazyPut(() => EnableIgnoringBatteryOptimizationsUseCase());
    Get.lazyPut(() => ShouldAutoOpenPlayerUseCase());
    Get.lazyPut(() => SetAutoOpenPlayerUseCase());
    Get.lazyPut(() => IsPipedLinkedUseCase());
    Get.lazyPut(() => UnlinkPipedUseCase());
    Get.lazyPut(() => ResetAppSettingsToDefaultUseCase());
    Get.lazyPut(() => ShouldStopPlaybackOnSwipeAwayUseCase());
    Get.lazyPut(() => SetStopPlaybackOnSwipeAwayUseCase());
  }
}
